---
- name: Test one
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: test task
      debug: msg="Test message from main.yml"
    - name: Local command
      command: hostname
      register: output
    - debug: msg="{{output}}"
  roles:
    - roles1
